project/config/routes.rb
Rails.application.routes.draw do

  get 'dance_to_advance/DanceToAdvance'
  
  get 'falling_kals/fallingKals'

  get 'avatar/avatarPage'
   
  get 'kal_kombat/KalKombat'

  get 'fighting_game1/KalKombat'

  get 'bmi/bmiCalc'

  get 'minigames/desktop'

  get 'menu/start'

  root 'login#loginPage'
  get 'story_intro_page/storyIntroPage'

  get 'intro_story/IntroStoryViewer2'

  get 'login/loginPage'

  get 'newuser/newUserPage' => 'newuser#newUserPage'

  

end

project/app/controllers/avatar_controller.rb
class AvatarController < ApplicationController
  def avatarPage
  end
end

project/app/controllers/dance_to_advance_controller.rb
class DanceToAdvanceController < ApplicationController
  def DanceToAdvance
  end
end

project/app/controllers/falling_kals_controller.rb
class FallingKalsController < ApplicationController
  def fallingKals
  end
end

project/app/controllers/fighting_game1_controller.rb
class FightingGame1Controller < ApplicationController
  def KalKombat
  end
end

project/app/controllers/kal_kombat_controller.rb
class KalKombatController < ApplicationController
  def KalKombat
  end
end

project/app/controllers/kalkombat_controller.rb
class KalkombatController < ApplicationController
  def kalkombat
  end
end

project/app/helpers/avatar_helper.rb
module AvatarHelper
end

project/app/helpers/dance_to_advance_helper.rb
module DanceToAdvanceHelper
end

project/app/helpers/falling_kals_helper.rb
module FallingKalsHelper
end

project/app/helpers/fighting_game1_helper.rb
module FightingGame1Helper
end

project/app/helpers/kal_kombat_helper.rb
module KalKombatHelper
end

project/app/helpers/kalkombat_helper.rb
module KalkombatHelper
end

project/app/views/avatar/avatarPage.html.erb
<html>
    <head>
    <style>
        #chart {
            display: table;
            //border: 5px solid black;
            height: 150px;
        }
        .tablerow {
            display: table-row;
            //border: 5px solid black;
        }
        .tablecell {
            display: table-cell;
            border: 2px solid black;
            //height: 10px;
        }
    </style>
    <script>
        var username;
        var user;
    </script>
    </head>
    <body>
        <h1>Avatar</h1>
        <form>
            <input type = "radio" id = "male" name = "gender" value = "male">Male
            <input type = "radio" id = "female" name = "gender" value = "female">Female <br />
            <input id = "weight" type = "number" name = "weight">lbs
            <input id = "height" type = "number" name = "height">ft.
            <input type = "button" id = "submit" value = "submit" onclick = "bmiFunction()">
        </form>
        <div id = "image"> Avatar</div></br>
        <div id = "chart">
            <div class = "tablerow">
                <div id = "avatarBmi" class = "tablecell"></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>BMI</p></div>
                <div class = "tablecell"><p>Weight Status</p></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>Below 18.5</p></div>
                <div class = "tablecell"><p>Underweight</p></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>18.5-24.9</p></div>
                <div class = "tablecell"><p>Normal</p></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>25.0-29.9</p></div>
                <div class = "tablecell"><p>Overweight</p></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>30.0 and Above</p></div>
                <div class = "tablecell"><p>Obese</p></div>
            </div>
        </div>
        <a href='../minigames/desktop?username='+username><input type = "button" value = "Go to Game Map"></a>
        <script>
            $(document).ready( function() {
                username = getURLParameter('username');
                user = JSON.parse(localStorage[username]);
                function getURLParameter(name) {
                    return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search)||[,""])[1].replace(/\+/g, '%20'))||null;
                };
            });
            function bmiFunction() {
                var inPerFoot = 12;
                var pounds = document.getElementById("weight").value;
                var inches = document.getElementById("height").value * inPerFoot;
                var bmi = (pounds / (Math.pow(inches, 2))) * 703;
                if (document.getElementById("male").checked) {
                    if (bmi < 18.5) {
                       document.getElementById("image").innerHTML = "<img src = '../../assets/anorexicMale.png'>";
                    }
                    if (bmi >= 18.5 && bmi < 25.0) {
                        document.getElementById("image").innerHTML = "<img src = '../../assets/normalWeightMale.png'>";
                    }
                    if (bmi >= 25.0 && bmi < 30.0) {
                        document.getElementById("image").innerHTML = "<img src = '../../assets/chubbyMale.png'>";
                    }
                    if (bmi >= 30.0) {
                        document.getElementById("image").innerHTML = "<img src = '../../assets/obeseMale.png'>";
                    }
                }
                if (document.getElementById("female").checked) {
                     if (bmi < 18.5) {
                         document.getElementById("image").innerHTML = "<img src = '../../assets/anorexicFemale.png'>";
                     }
                     if (bmi >= 18.5 && bmi < 25.0) {
                         document.getElementById("image").innerHTML = "<img src = '../../assets/normalWeightFemale.png'>";
                     }
                     if (bmi >= 25.0 && bmi < 30.0) {
                         document.getElementById("image").innerHTML = "<img src = '../../assets/chubbyFemale.png'>";
                     }
                     if (bmi >= 30.0) {
                         document.getElementById("image").innerHTML = "<img src = '../../assets/obeseFemale.png'>";
                     }
                }
                document.getElementById("avatarBmi").innerHTML = bmi;
            }

        </script>
    </body>
</html>

project/app/views/bmi/bmiCalc.html.erb
<html>
    <head>
    <style>
        #chart {
            display: table;
            //border: 5px solid black;
            height: 150px;
        }
        .tablerow {
            display: table-row;
            //border: 5px solid black;
        }
        .tablecell {
            display: table-cell;
            border: 2px solid black;
            //height: 10px;
        }
    </style>
    </head>
    <body>
        <h1>BMI Calculator</h1>
        <form>
            <input type = "radio" id = "male" name = "gender" value = "male">Male
            <input type = "radio" id = "female" name = "gender" value = "female">Female <br />
            <input id = "weight" type = "number" name = "weight">lbs
            <input id = "height" type = "number" name = "height">ft.
            <input type = "button" id = "submit" value = "submit" onclick = "bmiFunction()">
        </form>
        <div id = "image"> Avatar</div></br>
        <div id = "chart">
            <div class = "tablerow">
                <div id = "avatarBmi" class = "tablecell"></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>BMI</p></div>
                <div class = "tablecell"><p>Weight Status</p></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>Below 18.5</p></div>
                <div class = "tablecell"><p>Underweight</p></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>18.5-24.9</p></div>
                <div class = "tablecell"><p>Normal</p></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>25.0-29.9</p></div>
                <div class = "tablecell"><p>Overweight</p></div>
            </div>
            <div class = "tablerow">
                <div class = "tablecell"><p>30.0 and Above</p></div>
                <div class = "tablecell"><p>Obese</p></div>
            </div>
        </div>
        <a href="../avatar/avatarPage"><input type = "button" value = "Return to Avatar Profile"></a>
        <script>
            function bmiFunction() {
                var inPerFoot = 12;
                var pounds = document.getElementById("weight").value;
                var inches = document.getElementById("height").value * inPerFoot;
                var bmi = (pounds / (Math.pow(inches, 2))) * 703;
                if (document.getElementById("male").checked) {
                    if (bmi < 18.5) {
                       document.getElementById("image").innerHTML = "<img src = '../../assets/anorexicMale.png'>";
                    }
                    if (bmi >= 18.5 && bmi < 25.0) {
                        document.getElementById("image").innerHTML = "<img src = '../../assets/normalWeightMale.png'>";
                    }
                    if (bmi >= 25.0 && bmi < 30.0) {
                        document.getElementById("image").innerHTML = "<img src = '../../assets/chubbyMale.png'>";
                    }
                    if (bmi >= 30.0) {
                        document.getElementById("image").innerHTML = "<img src = '../../assets/obeseMale.png'>";
                    }
                }
                if (document.getElementById("female").checked) {
                     if (bmi < 18.5) {
                         document.getElementById("image").innerHTML = "<img src = '../../assets/anorexicFemale.png'>";
                     }
                     if (bmi >= 18.5 && bmi < 25.0) {
                         document.getElementById("image").innerHTML = "<img src = '../../assets/normalWeightFemale.png'>";
                     }
                     if (bmi >= 25.0 && bmi < 30.0) {
                         document.getElementById("image").innerHTML = "<img src = '../../assets/chubbyFemale.png'>";
                     }
                     if (bmi >= 30.0) {
                         document.getElementById("image").innerHTML = "<img src = '../../assets/obeseFemale.png'>";
                     }
                }
                document.getElementById("avatarBmi").innerHTML = bmi;
            }
            
        </script>
    </body>
</html>

project/app/views/dance_to_advance/DanceToAdvance.html.erb
<html> <head>
	<link rel="stylesheet" type="text/css" href="../../assets/dance_to_advance.css" media="screen"/>
        <script>
            var username;
            var user;
        </script>
        <script type="text/javascript" src="../../assets/dance_to_advance.js"></script>
        <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
        <! The app is the root folder. -->


    </head>
    <body id = "danceArea">
            <div id = "welcome" style="text-align: right; color: white; margin-right: 10%;"></div>
	    <!-- Simple audio playback -->
        <audio src="../../assets/02_-_Johann_Strauss_II_-_On_The_Beautiful_Blue_Danube_-_Waltz,_Op.314(Extract).mp3" autoplay>
            Your browser does not support the <code>audio</code> element.
        </audio>

		<title>Dance To Advance</title>
        <center><h1>Dance To Advance</h1>
		<h2> You need to dance for KAL in order to advance to the next stage. <br>
		If KAL decides your dance is worthy, KAL will allow you to advance to the next level. <br> KAL says: "Good luck puny human! MWAHAHA!"</h2>
         <div id = "image"></div>
				<input type = "button" id ="startButton"  onclick="danceWait()" value = "Start Dancing To Advance">		 
				<button type="button" id="judgeButton" style= "display:none" onclick="judge()">Click me to be judged</button>
				<input type = "button" id ="advanceButton" style= "display:none" onclick="parent.location='../minigames/desktop?username='+username" value = "Advance to the next level">
			
				<p>
				<p id="log" style="padding: 5px; margin: 5px; height: 0px; text-align: center;" ></p>
<p>
<p>
<p>
<P>
<P>
<P>
		</center>
        <script>
            $(document).ready( function() {
                username = getURLParameter('username');
                document.getElementById('welcome').innerHTML = "Welcome "+username;
                user = JSON.parse(localStorage[username]);
                function getURLParameter(name) {
                    return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search)||[,""])[1].replace(/\+/g, '%20'))||null
                };
            }); 

            $(window).on('load resize', function(){

                var w = $(window).width();
                var h = $(window).height();

                $('#danceArea').height(h);

            });
       </script> 
  </body>
</html>

project/app/views/fighting_game1/KalKombat.html.erb
<h1>FightingGame1#KalKombat</h1>
<p>Find me in app/views/fighting_game1/KalKombat.html.erb</p>

project/app/views/kal_kombat/KalKombat.html.erb

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html lang="en">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>KAL Kombat</title>
        <link rel="stylesheet" type="text/css" href="../../assets/kal_kombat.css" media="screen"/>
        <!-- This section is specific to this page, so we keep it
             out of the external, presumably reusable, JavaScript file. -->
        <script type="text/javascript">
            var username;
            var user; 
            /**
              * This is a "glue" function that grabs information from
              * the Web page and passes it to the Web drawing "library."
            */
            var addRectangleFromForm = function() {
                var form = document.getElementById("rectForm");
                var left = parseInt(form.left.value);
                var top = parseInt(form.top.value);
                var width = parseInt(form.width.value);
                var height = parseInt(form.height.value);
                addRectangle(left, top, width, height, form.name.value);
            };
        </script>
        <script type="text/javascript" src="../../assets/kal_kombat.js"></script>
		
		<meta charset="utf-8">
		<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
		<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
		<script src="http://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
		<link rel="stylesheet" href="/resources/demos/style.css">
		<style>
		#draggable { width: 100px; height: 100px; padding: 0.5em; float: left: 250px; margin: 10px 10px 10px 0; }
		#droppable { width: 150px; height: 150px; padding: 0.5em; float: left:200px; margin: 10px; }
				
		</style>

		
    </head>
    
    <body id ="KALKombat">
        <!-- Simple audio playback -->
        <audio src="../../assets/metal_monkeys.mp3" autoplay>
            Your browser does not support the <code>audio</code> element.
        </audio>
        <!-- This is the area in which the drawing will take place. -->
        <div id = "welcome" style="text-align: right; color: green; margin-right: 10%;"></div>
        <p id="playerlog" style="padding: 5px; margin: 5px; height: 0px; text-align: center;" >Game Log</p>
        <p id="opplog"style="padding: 20px; margin: 20px; text-align: center;"></p>

        <div id="drawingArea" style="width=100%; height: 500px; margin-top: 100px;">
        
				<!-- choices of opponent and player -->
					<button type="button" id="selectCodeMonkeyPlayer" style= "margin-left: 550px; margin-top: 240px;" onclick="selectCodeMonkeyPlayer()">Click me to have Code Monkey fight for you.</button>
					<button type="button" id="selectMalePlayer" style= "margin-left: 500px; margin-top: 10px;" onclick="selectMalePlayer()">Click me to play as a male.</button>
					<button type="button" id="selectFemalePlayer" onclick="selectFemalePlayer()">Click me to play as a female.</button>
					<button type="button" id="selectKalOpponent" style= "margin-left: 500px; margin-top: 10px;" onclick="selectKalOpp()">Click me to fight KAL.</button>
					<button type="button" id="selectAlienKal" style = "margin-left: 15px;" onclick="selectAlienKalOpp()">Click me to fight Alien Minion Kal.</button>
				<!-- note: margin- (eg. margin-left, margin-top etc.) measures distance from nearest object to the object itself -->	
					
				<!-- player image -->
				<div id="playerImage" class="playerImage"     
                 style="left: 60px; top: 90px; width: 450px; height: 600px;">You:<div id="playerHP">100</div><img src="/assets/FightingNormalWeightFemale.png" alt="FemaleFighterPlayer"></img>
				</div>  


            <div id="leftkick" class="leftKick" 
                 style="left: 10px; top: 550px; width: 180px; height: 120px;">
				 Kick</div>
    
            <div id="rightkick" class="rightKick" 
                 style="left: 400px; top: 550px; width: 180px; height: 120px;">
				 Kick</div>

            <div id="leftpunch" class="leftPunch"
                 style="left: 20px; top: 240px; width: 110px; height: 120px;">
				 Punch</div>
                 
            <div id="rightpunch" class="rightPunch"
                 style="left: 410px; top: 240px; width: 110px; height: 120px;">
				 Punch</div>                              
        
            <div id="heal" class="heal"
                 style="left: 214px; top: 700px; width: 175px; height: 170px;">
				 Heal</div>                 

                 
            <div id="opponent" class="opponent"
                 style="left: 820px; top: 90px; width: 450px; height: 600px;">Opponent:<div id="opponentHP">100</div><img src="/assets/tinyAlienCuteKal.gif" alt="Alien KAL"></img></div>                       
        </div>
        
    

        <!-- "Set up" the Web page. -->
        <script type="text/javascript">

// Note the reference to "drawingArea" above.
setDrawingArea(document.getElementById("drawingArea"));
        </script>
		
	

		
    </body>
         <script>
            $(document).ready( function() {
                username = getURLParameter('username');
                document.getElementById('welcome').innerHTML = "Welcome "+username;
                user = JSON.parse(localStorage[username]);
                function getURLParameter(name) {
                    return decodeURIComponent((new RegExp('[?|&]' + name + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search)||[,""])[1].replace(/\+/g, '%20'))||null
                };
            }); 
       </script>
</html>

project/app/views/login/loginPage.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Kalventure Login Page</title>
        <link rel="stylesheet" type="text/css" href="../../assets/loginpage.css" media="screen" />
    </head>
    <body id = "loginPage">
        <h1>Welcome to Kalventure!</h1>
        <h2>Login...if you dare...</h2>
        <div style="text-align:center">
        <table>
        <%= form_for :login, method: :get, url: menu_start_url do |f| %>
          <tr><td>
        <div style="text-align:left">
              <%= f.label :Username %>
              <%= f.text_field :username %>
            <!-- input type="text" name="user" maxlength = 8 -->
            <!-- Password --><br />
              <%= f.label :Password %>
              <%= f.text_field :pwd %>
        </div>
              <%= f.submit "Login"%>

           <!-->
            <!--input type="password" name="pwd" maxlength = 8--><!--br /-->
            <!--a href="../menu/start"--><!--input type = "button" value = "Login"--><!--/a--><!--br /-->
           <!-->
        </td></tr>
        <% end %>

        <tr><td>
        <div style="text-align:center">
        <br>
        New User? Sign up here!
        </div>
         <a href="../newuser/newUserPage"><input type = "button" value = "Sign Up"></a>
        </table>
    </body>
</html>

project/app/views/login/newuserpage.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>New User Signup</title>
        <link rel="stylesheet" href="newuserpage.css">
    </head>
	<script>
	function addToDb(value) {

	   if(typeof(Storage) !== "undefined") {
	   
	   users = new Array(clickcount);
	 
        if (localStorage.value) {
            localStorage.clickcount = Number(localStorage.clickcount)+1;
			localStorage.users[clickcount] = value;
        } else {
            localStorage.clickcount = 1;
			localStorage.users[clickcount-1] = value;
        }
        document.getElementById("result").innerHTML = "Hi user"+ localStorage.value +"You have clicked the button " + localStorage.clickcount + " time(s).";
		users[clickcount] = new Cell (value);
		
    } else {
        document.getElementById("result").innerHTML = "Sorry, your browser does not support web storage...";
    }
	
	}
	
	function reset(){
	  if(typeof(Storage) !== "undefined"){
	    localStorage.clickcount = 0; 
	    localStorage.users = new Array(clickcount+1);
	  } else{
	     document.getElementById("result").innerHTML = "Sorry, your browser does not support web storage.";
	  }
	}
	
	</script>
	
    <body>
        <script>
        function addToDb(value) {

           if(typeof(Storage) !== "undefined") {

           users = new Array(clickcount);

        if (localStorage.value) {
            localStorage.clickcount = Number(localStorage.clickcount)+1;
                        localStorage.users[clickcount] = value;
        } else {
            localStorage.clickcount = 1;
                        localStorage.users[clickcount-1] = value;
        }
        document.getElementById("result").innerHTML = "Hi user"+ localStorage.value +"You have clicked the button " + localStorage.clickcount + " time(s).";
                users[clickcount] = new Cell (value);

    } else {
        document.getElementById("result").innerHTML = "Sorry, your browser does not support web storage...";
    }

        }

        function reset(){
          if(typeof(Storage) !== "undefined"){
            localStorage.clickcount = 0;
            localStorage.users = new Array(clickcount+1);
          } else{
             document.getElementById("result").innerHTML = "Sorry, your browser does not support web storage.";
          }
        }

        </script>
        <h1>First Time Kalventurer? Sign up now!</h1>
        <form>
            First Name<br /> 
            <input type="text" name="first"><br />
            Last Name<br />
            <input type="text" name="last"><br />
            Email<br />
            <input type="email" name="email" placeholder = "i.e. abc@gmail.com"><br />
            Pick your Username<br />
            <input type="text" name="newUser" maxlength = 8><br />
            Create a password<br />
            <input type="password" name="newPass" maxlength = 8><br />
            Confirm your password<br />
            <input type="password" name="confPass" maxlength = 8><br />
            <p><button onclick="reset()" type="button">reset!</button></p>
            <input id = "submitButton" type = "Submit" value = "Sign Up" onclick="clickCounter()">
			<p><button onclick="reset()" type="button">reset!</button></p>
            <input onclick = "clickCounter()" type= "Submit" value = "Sign Up!">
			<button onclick="clickCounter()" type="button">Click me!</button>
        </form>
		
		
		document.getElementById("submitButton").onclick= "addToDb(value)";
		<div id="result"></div>
		
    </body>
</html>